=== vohoaiviet/lumens/lumens/lumens-client/src/main/resources/com/lumens/service/config/datasource.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/datasource.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Datasources SYSTEM "datasource.dtd">

    <Datasources>
    ...
    </Datasources>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Datasources (Datasource)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Datasource (Parameters|ClassName|ComponentIcon|Icon|Name|ID)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ID (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Icon (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ComponentIcon (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ClassName (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Parameters (Parameter)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter
    encrypted CDATA #IMPLIED
    javatype CDATA #IMPLIED
    name CDATA #IMPLIED
    id CDATA #IMPLIED
  >

=== vohoaiviet/lumens/lumens/lumens-client/src/main/resources/com/lumens/service/config/datasource.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Datasources SYSTEM "datasource.dtd">
<Datasources>
    <Datasource>
        <ID>webserviceID</ID>
        <Name>Web Service (SOAP)</Name>
        <Icon>soap.png</Icon>
        <ComponentIcon>datasource/32/soap.png</ComponentIcon>
        <ClassName>com.lumens.connector.webservice.WebServiceConnector</ClassName>
        <Parameters>
            <Parameter id="WSDL" name="WSDL address" javatype="java.lang.String"/>
            <Parameter id="ProxyAddress" name="Proxy server" javatype="java.lang.String"/>
            <Parameter id="ProxyPort" name="Proxy port" javatype="java.lang.Integer"/>
            <Parameter id="User" name="User" javatype="java.lang.Integer"/>
            <Parameter id="Password" name="Password" javatype="java.lang.String" encrypted="true"/>
        </Parameters>
    </Datasource>
    <Datasource>
        <ID>databaseID</ID>
        <Name>Database</Name>
        <Icon>database.png</Icon>
        <ComponentIcon>datasource/32/database.png</ComponentIcon>
        <ClassName>com.lumens.connector.database.DatabaseConnector</ClassName>
        <Parameters>
            <Parameter id="Server" name="Database server" javatype="java.lang.String"/>
            <Parameter id="Port" name="Database port" javatype="java.lang.Integer"/>
            <Parameter id="User" name="User" javatype="java.lang.Integer"/>
            <Parameter id="Password" name="Password" javatype="java.lang.String" encrypted="true"/>
        </Parameters>
    </Datasource>
</Datasources>
